[package]
name = "Helloworldsampleenclave"
version = "1.0.0"
authors = ["The Teaclave Authors"]

[lib]
name = "helloworldsampleenclave"
crate-type = ["staticlib"]

[features]
default = []


[dependencies]

dusk-plonk = {path = "/root/sgx/exp/lib/plonk"}
dusk-bls12_381 = {path = "/root/sgx/exp/lib/dusk-bls12_381-0.10.1", default-features = false, features = ["groups", "pairings", "endo"]}
dusk-jubjub = {path ="/root/sgx/exp/lib/dusk-jubjub-0.12.0-rc.0", default-features = false}
rand_core = {path = "/root/sgx/exp/lib/rand_core-0.6.3"}
sgx_tstd = {path = "/root/sgx/sgx_tstd"}
sgx_types = {path = "/root/sgx/sgx_types"}

# [target.'cfg(not(target_env = "sgx"))'.dependencies]
# sgx_types = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
# sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }






[patch.'https://github.com/apache/teaclave-sgx-sdk.git']
sgx_align_struct_attribute = { path = "../../../sgx_align_struct_attribute" }
sgx_alloc = { path = "../../../sgx_alloc" }
sgx_backtrace = { path = "../../../sgx_backtrace" }
sgx_backtrace_sys = { path = "../../../sgx_backtrace_sys" }
sgx_build_helper = { path = "../../../sgx_build_helper" }
sgx_cov = { path = "../../../sgx_cov" }
sgx_crypto_helper = { path = "../../../sgx_crypto_helper" }
sgx_demangle = { path = "../../../sgx_demangle" }
sgx_libc = { path = "../../../sgx_libc" }
sgx_no_tstd = { path = "../../../sgx_no_tstd" }
sgx_rand = { path = "../../../sgx_rand" }
sgx_rand_derive = { path = "../../../sgx_rand_derive" }
sgx_serialize = { path = "../../../sgx_serialize" }
sgx_serialize_derive = { path = "../../../sgx_serialize_derive" }
sgx_serialize_derive_internals = { path = "../../../sgx_serialize_derive_internals" }
sgx_tcrypto = { path = "../../../sgx_tcrypto" }
sgx_tcrypto_helper = { path = "../../../sgx_tcrypto_helper" }
sgx_tdh = { path = "../../../sgx_tdh" }
sgx_tkey_exchange = { path = "../../../sgx_tkey_exchange" }
sgx_tprotected_fs = { path = "../../../sgx_tprotected_fs" }
sgx_trts = { path = "../../../sgx_trts" }
sgx_tse = { path = "../../../sgx_tse" }
sgx_tseal = { path = "../../../sgx_tseal" }
sgx_tstd = { path = "../../../sgx_tstd" }
sgx_tunittest = { path = "../../../sgx_tunittest" }
sgx_types = { path = "../../../sgx_types" }
#sgx_ucrypto = { path = "../../../sgx_ucrypto" }
sgx_unwind = { path = "../../../sgx_unwind" }
#sgx_urts = { path = "../../../sgx_urts" }
